import type { SeedProfile } from "./profile-types";

export const electricianSeed: SeedProfile = {
  business: {
    slug: "sample-electrician",
    mode: "service_business",
    businessName: "Sample Electric Co.",
    phone: "(555) 010-3300",
    email: "hello@sampleelectricco.com",
    serviceArea: "Local service area",
    primaryCtaText: "Request Electrical Service",
    secondaryCtaText: "Request an Estimate",
    brandPrimary: "#0f766e",
    brandSecondary: "#f59e0b",
    brandAccent: "#0f172a",
    timezone: "America/Denver",
    branding: {
      logoType: "wordmark",
      tone: "professional, safety-first, responsive",
    },
    contactRouting: {
      notifyEmails: ["hello@sampleelectricco.com"],
    },
    isActive: true,
  },
  services: [
    {
      name: "Electrical Service Call",
      slug: "electrical-service-call",
      summary: "General troubleshooting, diagnostics, and electrical service work.",
      description:
        "Request an on-site service visit for common residential or light commercial electrical issues.",
      priceLabel: "Call for pricing",
      sortOrder: 1,
      isFeatured: true,
      isActive: true,
    },
    {
      name: "Panel / Breaker Help",
      slug: "panel-breaker-help",
      summary: "Panel and breaker troubleshooting, repair planning, and safety checks.",
      description:
        "Get support for tripping breakers, panel concerns, or electrical load and safety questions.",
      priceLabel: "Estimate available",
      sortOrder: 2,
      isFeatured: false,
      isActive: true,
    },
    {
      name: "Outlet, Switch, and Fixture Work",
      slug: "outlet-switch-fixture-work",
      summary: "Installations, replacements, and repairs for common electrical fixtures.",
      description:
        "Request help with outlets, switches, light fixtures, and related electrical updates.",
      priceLabel: "Estimate available",
      sortOrder: 3,
      isFeatured: false,
      isActive: true,
    },
    {
      name: "Estimate Request",
      slug: "electrical-estimate-request",
      summary: "Project estimate before booking larger electrical work.",
      description:
        "Share your project details and we will follow up with a scoped estimate and next steps.",
      priceLabel: "Free estimate",
      sortOrder: 4,
      isFeatured: false,
      isActive: true,
    },
    {
      name: "Emergency Electrical Request",
      slug: "emergency-electrical-request",
      summary: "Priority follow-up for urgent electrical problems.",
      description:
        "Use this option when you have urgent electrical issues that need fast response.",
      priceLabel: "Priority response",
      sortOrder: 5,
      isFeatured: false,
      isActive: true,
    },
  ],
  intakeQuestions: [
    {
      audience: "customer",
      label: "What electrical service do you need?",
      fieldKey: "electrical_service_needed",
      fieldType: "textarea",
      helpText: "Briefly describe the issue or project request.",
      isRequired: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Is this an emergency?",
      fieldKey: "is_emergency",
      fieldType: "select",
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      isRequired: true,
      sortOrder: 2,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Where is the work located?",
      fieldKey: "work_location",
      fieldType: "text",
      placeholder: "Street address and city",
      isRequired: true,
      sortOrder: 3,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Is power currently out or partially out?",
      fieldKey: "power_outage_status",
      fieldType: "select",
      options: [
        { label: "Fully out", value: "fully_out" },
        { label: "Partially out", value: "partially_out" },
        { label: "No outage", value: "no_outage" },
        { label: "Not sure", value: "not_sure" },
      ],
      isRequired: true,
      sortOrder: 4,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Preferred appointment window",
      fieldKey: "preferred_appointment_window",
      fieldType: "select",
      options: [
        { label: "Morning", value: "morning" },
        { label: "Afternoon", value: "afternoon" },
        { label: "Evening", value: "evening" },
      ],
      isRequired: false,
      sortOrder: 5,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Are there photos or extra details you want to mention?",
      fieldKey: "photos_or_extra_details",
      fieldType: "textarea",
      helpText:
        "File uploads are not enabled yet. Please describe any photo details in text.",
      isRequired: false,
      sortOrder: 6,
      isActive: true,
    },
  ],
  admin: {
    name: "Sample Electric Owner",
    email: "owner@sampleelectricco.com",
    passwordHash: "seed-script-overrides-this",
    role: "owner",
    isActive: true,
  },
};
