import type { SeedProfile } from "./profile-types";

export const serviceBusinessSeed: SeedProfile = {
  business: {
    slug: "sample-service-business",
    mode: "service_business",
    businessName: "Sample Service Co.",
    phone: "(555) 010-2200",
    email: "hello@sampleserviceco.com",
    serviceArea: "Local service area",
    primaryCtaText: "Request Service",
    secondaryCtaText: "Request an Estimate",
    brandPrimary: "#0f766e",
    brandSecondary: "#f59e0b",
    brandAccent: "#0f172a",
    timezone: "America/Denver",
    branding: {
      logoType: "wordmark",
      tone: "friendly, reliable, local service",
    },
    contactRouting: {
      notifyEmails: ["hello@sampleserviceco.com"],
    },
    isActive: true,
  },
  services: [
    {
      name: "Service Call",
      slug: "service-call",
      summary: "General on-site visit to diagnose and complete common service work.",
      description:
        "Request a standard service call for troubleshooting, repairs, or routine job support.",
      priceLabel: "Call for pricing",
      sortOrder: 1,
      isFeatured: true,
      isActive: true,
    },
    {
      name: "Estimate Request",
      slug: "estimate-request",
      summary: "Project estimate for upcoming work before scheduling a full job.",
      description:
        "Share your project details and we will follow up with an estimate and recommended next steps.",
      priceLabel: "Free estimate",
      sortOrder: 2,
      isFeatured: false,
      isActive: true,
    },
    {
      name: "Emergency Request",
      slug: "emergency-request",
      summary: "Urgent request support for time-sensitive service issues.",
      description:
        "Use this option when you need priority follow-up for urgent service needs.",
      priceLabel: "Priority response",
      sortOrder: 3,
      isFeatured: false,
      isActive: true,
    },
  ],
  intakeQuestions: [
    {
      audience: "customer",
      label: "What service do you need?",
      fieldKey: "service_needed",
      fieldType: "textarea",
      helpText: "Briefly describe the service, issue, or project request.",
      isRequired: true,
      sortOrder: 1,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Where is the work located?",
      fieldKey: "service_location",
      fieldType: "text",
      placeholder: "Street address and city",
      isRequired: true,
      sortOrder: 2,
      isActive: true,
    },
    {
      audience: "customer",
      label: "How urgent is this?",
      fieldKey: "urgency_level",
      fieldType: "select",
      options: [
        { label: "Emergency / ASAP", value: "emergency_asap" },
        { label: "Within 24-48 hours", value: "within_24_48_hours" },
        { label: "Within 1 week", value: "within_1_week" },
        { label: "Flexible timing", value: "flexible_timing" },
      ],
      isRequired: true,
      sortOrder: 3,
      isActive: true,
    },
    {
      audience: "customer",
      label: "Preferred appointment window",
      fieldKey: "preferred_appointment_window",
      fieldType: "select",
      options: [
        { label: "Morning", value: "morning" },
        { label: "Afternoon", value: "afternoon" },
        { label: "Evening", value: "evening" },
      ],
      isRequired: false,
      sortOrder: 4,
      isActive: true,
    },
  ],
  admin: {
    name: "Sample Service Owner",
    email: "owner@sampleserviceco.com",
    passwordHash: "seed-script-overrides-this",
    role: "owner",
    isActive: true,
  },
};
